scrape_configs:
  - job_name: 'whatthis'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'springdoitt'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.20.10.12:8080']